package.json, src/extension.ts, test/extension.test.ts, types/lcov-parse/index.d.ts
=> #6: add lcov-parse d.ts and cleanup skeleton code

src/extension.ts, src/gutters.ts, test/extension.test.ts, test/gutters.test.ts, types/lcov-parse/index.d.ts
=> Add lcov file reading and storage

README.md, package.json
=> Add basic keybindings for actions

README.md, package.json, src/config.ts
=> Add show options for gutter, line and ruler

README.md, package.json, src/config.ts, src/extension.ts, src/gutters.ts, src/reporter.ts, src/statusbartoggler.ts, test/gutters.test.ts, test/reporter.test.ts
=> Add status icon feature and cleanup

src/config.ts, test/config.test.ts
=> Add more test coverage to config component

src/gutters.ts
=> Watch and remove watch do their singular cousin's action

package-lock.json, package.json, src/reporter.ts, src/wrappers/request.ts, test/reporter.test.ts
=> Fix crash when reporter throws an error.  Also adds a pretty command to use tslint fix.

package-lock.json, package.json, src/coverageservice.ts, src/helpers.ts, src/renderer.ts, src/topSectionFinder.ts, test/findIntersection.test.ts, test/normalizeFileName.test.ts, test/renderer.test.ts, test/topSectionFinder.test.ts
#137 
Splitting up the renderer.ts file to facilitate testing.
=> #137 - Splitting TopSectionFinder from Renderer and adding unit tests to both. (WIP)

package.json, src/extension/config.ts, src/files/filesloader.ts, test/coverage-system/coverage.test.ts, test/coverage-system/renderer.test.ts, test/extension/statusbartoggler.test.ts, test/fakeConfig.test.ts
Starting from this commit, ignored paths are able to be edited using the
extension settings
Not sure how to test this though
Closes #143
=> [#143] Add ignored path globs as a config

package.json, src/extension/config.ts, test/extension/config.test.ts, test/fakeConfig.test.ts
Closes #132. 
Maybe even more attributes can be removed.
=> Cleanup package.json extension attributes [#132]

src/files/coverageparser.ts
Running coverage-gutter on my project keeps failing with an error ```Error: Failed to parse string``` similar to what is described in the issue [Error Failed to parse string #150](https://github.com/ryanluker/vscode-coverage-gutters/issues/150). 
For me it turned out to be invalid lcov files in our project but there was no way to remedy this and no log to see which files were in error. I ran both ```npm test-unit``` and ```npm test-integration``` both worked but ```npm test``` fails but looks like that commands setup might not be correct.
=> Handle lcov file parsing errors

package-lock.json, package.json
=> Update npm modules based on critical issues alert

example/node/lcov.info, src/files/coverageparser.ts
=> Cleanup absolute finder and misc parser error flows

package-lock.json, src/coverage-system/coverageservice.ts, src/coverage-system/sectionFinder.ts, src/files/coverageparser.ts, test/coverage-system/topSectionFinder.test.ts
=> Move relative to absolute to file open for performance gains

src/coverage-system/coverage.ts, src/coverage-system/coverageservice.ts, src/coverage-system/renderer.ts, src/coverage-system/sectionFinder.ts, src/extension.ts, src/extension/config.ts, src/extension/gutters.ts, src/extension/statusbartoggler.ts, src/files/coverageparser.ts, src/files/filesloader.ts, test/extension/config.test.ts, test/mocks/fakeConfig.ts
=> [#169] Add support for reloading config by workspace event

src/extension/gutters.ts, src/extension/statusbartoggler.ts, test/extension/statusbartoggler.test.ts
=> Change `statusBar.toggle` to receive the toggle state

package-lock.json, package.json
=> Increment dependency versions to fix xml parse

src/coverage-system/coverageservice.ts, src/coverage-system/sectionfinder.ts, src/helpers.ts, test/helpers.test.ts
Added caching for glob search so that filesystem operations are done only once per watch not once per section.
=> convertPartialPathsToAbsolute optimization

@types/cobertura-parse/index.d.ts, @types/jacoco-parse/index.d.ts, @types/lcov-parse/index.d.ts, src/coverage-system/renderer.ts, src/coverage-system/sectionfinder.ts, src/files/coverageparser.ts, test/coverage-system/renderer.test.ts, test/coverage-system/sectionfinder.test.ts
@justarandomgeek FYI
Related Issue: #245 
Related PR: #246
=> Allow multiple sections per file path

example/php/composer.json, example/php/cov.xml, example/php/src/testCoverage/testMain/main.php, example/php/src/testCoverage/testMain2/main2.php, example/php/src/testCoverage/testNoNamespace/main3.php, example/php/tests/mainTest.php, package-lock.json, package.json, test/extension.test.ts
https://github.com/ryanluker/vscode-coverage-gutters/issues/260#issuecomment-618812480
=> PHP: non-namespaced example

src/coverage-system/coverageservice.ts, test/extension.test.ts
=> Misc logging improvement and un-needed await cleanup

src/extension/gutters.ts, src/extension/webview.ts, test/extension/webview.test.ts
Webview.ts file created in the extension directory, and a
CSP header is being added to text before loading it to webview.html.
=> refactor: Webview creation logic in new module

.github/workflows/test.yml
Cleanup steps for linux.
Add nightly build and test (as per readme).
=> Cleanup test github action

.github/workflows/publish.yml
closes #225 
Add CD capabilities via GH action
=> Create publish.yml for github action publish

test/coverage-system/coverage.test.ts, test/coverage-system/coverageservice.test.ts, test/coverage-system/renderer.test.ts, test/coverage-system/sectionfinder.test.ts, test/extension.test.ts, test/extension/config.test.ts, test/extension/statusbartoggler.test.ts, test/extension/webview.test.ts, test/files/coveragefile.test.ts, test/files/coverageparser.test.ts, test/files/filesloader.test.ts, test/helpers.test.ts
Addresses the 4th point in #321.
=> Migrate all test assertions to expect

test/coverage-system/coverage.test.ts, test/coverage-system/coverageservice.test.ts, test/extension/config.test.ts, test/files/coverageparser.test.ts, test/files/filesloader.test.ts
Closes #321 by addressing the remaining checkboxes.
I have annotated the PR where I thought that it was appropriate.
As usual LMK if you'd like to see any changes or need clarification on why decisions where made 👍🏻.
=> Refactor existing manual mocks

.github/workflows/test.yml, @types/@cvrg-report/clover-json/index.d.ts, package-lock.json, package.json, src/coverage-system/coverageservice.ts, src/extension/config.ts, src/extension/gutters.ts, src/extension/statusbartoggler.ts, src/extension/webview.ts, src/files/coveragefile.ts, src/files/coverageparser.ts, test/coverage-system/coverage.test.ts, test/coverage-system/coverageservice.test.ts, test/coverage-system/sectionfinder.test.ts, test/extension/config.test.ts, test/files/filesloader.test.ts, tsconfig.json
=> Attempt to get actions running again

README.md
Sharing a bit of the visibility around who helps maintain this extension (not fair for just me to be present!)
Not everyone had a website to promote though, so please ping here with the preferred link (github, twitter, mastadon, etc).
https://github.com/ryanluker/vscode-coverage-gutters/graphs/contributors
Specifically looking for info from:
@mattseddon 
@timagixe 
@pdfowler 
@amatosov-rbx 
I will leave the PR open until the next release to give people time to get back to me 😁.
=> Add maintainer websites for +5 commits

example/java/my-app/pom.xml
Fix error:
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
Fixes issue:  https://github.com/ryanluker/vscode-coverage-gutters/issues/415
=> Update version in pom. Bugfix jacocoAccess

example/powershell/READMDE.md, example/powershell/src/Appointment.psm1, example/powershell/src/Calendar.psm1, example/powershell/src/coverage.xml, example/powershell/tests/Calendar.Tests.ps1, example/powershell/tests/RunTests.ps1
This pull request adds an example for powershell 5.1 and pester as introduced by Issue #456.
=> Add powershell example

.github/workflows/publish.yml
#430 Updates the publish action from v0 -> v2.
=> Update publish extension action
