ryanluker/vscode-coverage-gutters

.gitignore, example/package.json, example/test-coverage.js, example/test.js, package.json, src/extension.ts, src/gutters.ts, test/extension.test.ts, test/gutters.test.ts
=> Add renderIndicators and remove coverage command

README.md, package.json, src/config.ts, src/gutters.ts, src/indicators.ts, src/lcov.ts, src/wrappers/fs.ts, src/wrappers/lcov-parse.ts, src/wrappers/vscode.ts, test/indicators.test.ts, test/lcov.test.ts
=> Add relative lcov path support

example/test-coverage.js, example/test.js, images/gutter-icon-dark.svg, images/no-gutter-icon-dark.svg, images/no-gutter-icon-light.svg, images/partial-gutter-icon-dark.svg, images/partial-gutter-icon-light.svg, package.json, src/config.ts, src/gutters.ts, src/indicators.ts, test/config.test.ts, test/extension.test.ts, test/gutters.test.ts, test/indicators.test.ts, test/integration/indicators.test.ts, test/integration/lcov.test.ts, test/lcov.test.ts, test/system/extension.test.ts, types/lcov-parse/index.d.ts
coverage being shown for full, partial and none
=> Enhanced coverage displaying

.vscodeignore, src/gutters.ts, src/lcov.ts, test/lcov.test.ts
=> Display caught errors and prevent lcov error

README.md, example/test-coverage.js, example/test.js, package.json, src/config.ts, src/extension.ts, src/gutters.ts, src/reporter.ts, src/statusbartoggler.ts, test/gutters.test.ts, test/indicators.test.ts, test/lcov.test.ts, test/statusbartoggler.test.ts
=> Add option to hide status bar item and general cleanup

images/gutter-icon-dark.svg, images/no-gutter-icon-dark.svg, images/partial-gutter-icon-dark.svg, package.json, src/config.ts
=> Update dark colours and show defaults

src/gutters.ts, src/lcov.ts
- unix environment was throwing errors when trying to preview lcov report with preview 1.1.0 release
=> Fix issue with unix style file paths

src/indicators.ts
On Windows the file paths in the cobertura XML report miss the drive letter ( see this issue here, https://github.com/OpenCppCoverage/OpenCppCoverage/issues/14 ). This PR should fix the issue.
=> Fix cobertura parsing on Windows

package-lock.json, package.json
Fixes 3 identified vulnerabilities: `found 3 vulnerabilities (1 low, 1 high, 1 critical)`
Upgrades jacoco-parse to v2, which is a backwards-breaking change.
=> Running - npm audit fix --force

README.md
I found it initially difficult to setup a python project from only reading the README.md in VSCode marketplace.
Linking to the working examples directory clears up the critical path for onboarding.
=> Link to examples directories in main README.md

package.json, src/coverage-system/coverageservice.ts, src/extension/config.ts, src/files/filesloader.ts, test/extension.test.ts, test/extension/config.test.ts, test/fakeConfig.test.ts
=> Add coverage file names config and cleanup historical method

src/extension/config.ts
Seems you just can't trust me to configure a vscode plugin I keep putting in dodgy config that breaks my coverage. I accidentally cleared the xml config filename which resulted in the [fileloader](https://github.com/ryanluker/vscode-coverage-gutters/blob/a3070176a5472766de998b5053a4d9197cf56a10/src/files/filesloader.ts#L48) attempting to load every file in my workspace resulting in this error:
```
[1543244667227][coverageservice]: INITIALIZING
[1543244667527][coverageservice]: LOADING
[1543244672779][coverageservice]: Loading 1237 file(s)
[1543244672782][gutters]: Error EISDIR: illegal operation on a directory, read
[1543244672782][gutters]: Stacktrace Error: EISDIR: illegal operation on a directory, read
[1543244672783][coverageservice]: RENDERING
[1543244672783][coverageservice]: READY …
```
=> Ignore empty coverage filenames

@types/cobertura-parse/index.d.ts, @types/jacoco-parse/index.d.ts, package-lock.json, package.json, src/coverage-system/coverageservice.ts, src/files/coverageparser.ts
=> Use proper latest version of cobertura parse

.editorconfig, src/files/coveragefile.ts, test/files/coveragefile.test.ts
Sometimes we may encounter an empty `lcov.info` file. Since we know
that an empty file can't contain valid coverage data, we simply
ignore it rather than unsuccessfully trying to load.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ryanluker/vscode-coverage-gutters/215)
=> Don't crash if we find empty lcov.info (#150)

package.json
There used to be options for this, not sure why it doesn't work anymore. This is the new implementation. 
It used to be several different config flags, but I combined it into one. I figured people would either want all of it or none. It also reduces clutter from too many options. However I noticed you had very fine-grain control for the existing options. Opinions?
Side note, it kind of bothers me that 2 of the config descriptions are Capitalized while the rest are not :(
See links below for details.
https://code.visualstudio.com/api/references/contribution-points#contributes.menus
https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts
Fixes #216.
=> Add config option for context menu commands

README.md, package.json, src/coverage-system/coverageservice.ts, src/extension/config.ts, src/files/filesloader.ts, test/files/filesloader.test.ts, test/mocks/fakeConfig.ts
=> Add manual coverage path option

.github/workflows/test.yml
**Related Issue**: #225 
Currently github actions do not fire on forked repositories. To fix this we need to simply add the `pull_request` event and a specific push one for only master.
https://help.github.com/en/articles/events-that-trigger-workflows#pull-request-events-for-forked-repositories
=> Refine when github actions are fired

src/coverage-system/sectionfinder.ts
workspaceFolder name with case-sensitive cause match failed
=> Bugfix: Normalize workspaceFolder name

package-lock.json, package.json, src/extension.ts, src/extension/statusbartoggler.ts, test/extension.test.ts
At the moment the commands are under a namespace called 'extension'. That's a little confusing for anyone trying to call those commands as we'd guess vscode-coverage-gutters or coverage-gutters (I'm not entirely sure which is the most correct, but either is better than having them prefixed extension.
Figured I'd raise it as a PR rather than an issue.
=> extension was meant to be extension name.

src/coverage-system/coverageservice.ts, test/coverage-system/coverageservice.test.ts
I would like to use manualCoverageFilePaths with a set of explicit lcov files and avoid glob lookups, in order to optimize coverage-gutter on big workspaces.
`createFileSystemWatcher` works well with the glob pattern which contains files inside and outside of the workspace and successfully watches files that are inside workspace folders
Update `listenToFileSystem` to listen for `manualCoverageFilePaths` if they are provided
```
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:43:02.577Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```
=> Make manualCoverageFilePaths watchable

package.json, src/coverage-system/coverageservice.ts, src/extension/config.ts, src/files/filesloader.ts, test/coverage-system/coverageservice.test.ts
On big workspaces (e.g. 12k directories, 74k files) recursive glob lookup `**` is very time consuming. Currently there is no way to avoid it via configuration options. 
`manualCoverageFilePaths` is the only option, however it eliminates any kind of glob lookup, which is not desired.
Introduce `coverageBaseDir` that allows users to fully customize lookup glob for coverage files
It defaults to `**`, so existing behavior is not going to change.
=> Make base glob configurable via coverageBaseDir

src/coverage-system/coverageservice.ts, src/extension.ts, src/extension/crashreporter.ts, src/extension/gutters.ts, src/extension/report.ts, src/files/coverageparser.ts
A new file report.ts that handles all codes dealing with crash
reporting and sentry init, was created in the extension directory.
The changes did not cause any side effects after running tests.
=> refactor: Creates new module for crash reporting

.github/workflows/test.yml, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, example/example.code-workspace, package-lock.json, package.json, test/index.ts, test/runTest.ts
Closes #263
@pdfowler Thanks a bunch for getting this process started!
I ended up finishing it as the old way was recently deprecated and producing a lot of errors in my email inbox.
=> Migrate to new vscode test and types/vscode

src/coverage-system/sectionfinder.ts, test/coverage-system/sectionfinder.test.ts
This PR fixes #252.
The change is to use the base name of the path for the workspace folder instead of the name, which defaults to the path's base name if a name hasn't been specified. I've tested that this works in my setup (VS Code 1.54.2 running on Linux), and have added unit tests to cover the cases where a name has or hasn't been specified.
=> Allow named workspace folders

package.json, src/extension/config.ts, test/extension/config.test.ts
I ran into an issue today whilst trying to update the colors of gutters' SVGs (same issue as detailed in #239).
These changes are designed to enable users to have permanently saved SVGs somewhere on disk.
=> Enable custom svgs to be provided via config options

test/runTest.ts
As discussed here: https://github.com/ryanluker/vscode-coverage-gutters/pull/310#issuecomment-846496483.
Change means that you can run the test suite from the command line whilst `vscode` is open. 👍🏻
=> Use insiders build for test suite

package-lock.json, package.json, src/coverage-system/coverageservice.ts, src/extension/statusbartoggler.ts, test/extension.test.ts, test/extension/statusbartoggler.test.ts
Closes #289.
~Feature works as expected but needs polished.~
@ryanluker thanks for having a look at the code whilst it was still in draft, I have refactored now and added an additional touch to alter the status bar tooltip text depending on the state of the workspace (watched vs unwatched).
Here is a v short demo (as it had to be under 10MB):
https://user-images.githubusercontent.com/37993418/121833778-66097a00-cd10-11eb-8be1-ad710bfc284e.mov
LMK if you'd like to see any changes.
Thanks,
=> Issue 289: Add line coverage to status bar

package-lock.json, package.json
This is related to, and should resolve #304.
I did not have time yet nor do I have the experience to run the tests for this.
=> replace cobertura parser with patched version

package-lock.json, package.json
https://github.com/ryanluker/vscode-coverage-gutters/issues/370#issuecomment-1120402680
According to [typescriptlang.org](https://www.typescriptlang.org/tsconfig#importHelpers), not using `importHelpers` "can result in code duplication if the same helper is used in many different modules". So use `tslib` might be a better solution.
The reason the unit tests are not failing is that unit tests use the development environment's `node_modules` when running.
Tested on my computer.
close #370
=> Add `tslib` as runtime dep

package-lock.json, package.json
Should fix #254 once the patch is applied to this extension repo.
- I think I oops'd my windows machine github line endings as the lock file has changed a lot 😓.
=> Upgrade cobertura parse to latest

.devcontainer/devcontainer.json, package-lock.json, package.json
closes #383 
@trenttobler
Background https://github.com/ryanluker/vscode-coverage-gutters/issues/383#issuecomment-1304714614
=> Adjust dev container and cobertura package install path

package.json, src/coverage-system/coverageservice.ts, src/extension.ts, src/extension/gutters.ts, test/extension.test.ts
- #378 
- Add new boolean to track current display state.
- Add command to show/hide coverage gutter based on boolean.
- Tests and code linting are passing via continuous integration checks.
=> feat: Add toggle command

package.json
Changes the activation event from startup to onStartupFinished.
It wasn't having a big impact on startup time (at only around 23 ms) but since it can be put off, figured why not. (I'm trying pretty hard to improve my VSC performance. ^-^')
Read the related issue for more info!
* Closes https://github.com/ryanluker/vscode-coverage-gutters/issues/388
=> chore: change activation event to onstartupfinished

src/coverage-system/coverage.ts, test/coverage-system/coverage.test.ts
- closes #381
- convert file path string to vscode.Uri to support changes in live preview
- resolves the exception mentioned in https://github.com/microsoft/vscode-livepreview/issues/384
=> fix(preview): pass vscode.uri to live preview

package.json
Fixes: #408
---
name: Pull Request
about: Submit new code for review
---
- A reference to a related issue in your repository.
- This should convince vscode to recognize the workspace level settings.
- @ryanluker
=> Declare settings scope as resource

.github/workflows/test.yml, package-lock.json, package.json, test/runTest.ts
For some reason the vscode (insiders latest) with windows-latest had started failing recently due to the following warning.
```
This version of D:\a\vscode-coverage-gutters\vscode-coverage-gutters\.vscode-test\vscode-win32-archive-1.79.0\Code.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
Failed to run tests
Error: Process completed with exit code 1.
```
=> Try to fix nightly build script for windows + latest vscode

src/coverage-system/coverageservice.ts
---
name: statusbar should report `Math.floor`
about: statusbar should report `Math.floor` instead of `Math.round`
---
- implements proposal in #423
- in a 200 line file with 1 missed line, statusbar would report 100%
coverage with `Math.round`, which is misleading; there is still one
missed line, so use `Math.floor` instead (which would report 99%
coverage)
- @ryanluker
=> statusbar reports floor of coverage (resolves #423)

src/coverage-system/renderer.ts
---
name: Fix `Illegal argument: line must be non-negative`
about: Fix `Illegal argument: line must be non-negative` error by ignoring detail whose line attribute is 0
---
- Fix https://github.com/ryanluker/vscode-coverage-gutters/issues/424
- Change the filter in the renferer to ignore detail whose line attribute is 0.
=> Fix `Illegal argument: line must be non-negative`

src/coverage-system/coverageservice.ts
When working in certain scenarios such as a split-view layout coverage for a file wasn’t displaying or updating if you switched to another file without actually focusing on the coverage file. For example, if one pane shows the coverage while another pane, which is in focus, controls which file is displayed in the first pane, the coverage pane would fail to refresh properly.
This pull request fixes that issue by changing the `listenToEditorEvents` listener from `onDidChangeActiveTextEditor` to `onDidChangeVisibleTextEditors`. As a result, coverage now updates correctly even when the file isn’t the active editor.
=> Changed the coverage updates from active to visible

src/files/filesloader.ts, test/files/filesloader.test.ts
This extension silently fails if a file in the `coverage-gutters.manualCoverageFilePaths` setting does not exist.
This PR filters out any files from that setting that do not exists and raises a warning to the user:
By the way, thanks for this extension!  Really useful!
=> ignore and warn on unknown manual coverage file paths

.github/workflows/test.yml, .gitignore, .vscode/launch.json, .vscodeignore, esbuild.js, package-lock.json, package.json, test/extension.test.ts, test/runTest.ts, tsconfig.json
#212 
Nothing too crazy here, mainly just following along with the migration guide / vscode extension development documentation.
https://code.visualstudio.com/api/working-with-extensions/bundling-extension#migrate-an-existing-extension
- vsce package (installed and confirmed it can display coverage)
- npm run test
- npm run build
=> Add esbuild to bundle and package the extension

package.json, src/coverage-system/coverageservice.ts, test/createTestPackageJson.ts, test/extension.test.ts, test/runTest.ts
Closes #479 
The underlying issue is that sinon cannot mock modules in the bundled `dist` folder. In order for this to work we need to copy the package.json from the root folder into the `out/` folder (generated by `compile-tests`) and update the `main` entry to point at `src/extension`.
I have taken the opportunity to update the tests in `extension.tests.ts` to ensure they are now testing the correct things.
=> copy (and update) package.json to out directory to enable mocking in integration tests
